# Configuration file for MegaLinter
#
# See all available variables at https://megalinter.io/latest/config-file/ and in
# linters documentation

EXCLUDED_DIRECTORIES:
  - "megalinter-reports"
  - "test"
  - ".idea"
# all, none, or list of linter keys
APPLY_FIXES: none

DISABLE_LINTERS:
  - CSHARP_ROSLYNATOR
DISABLE:
  # - COPYPASTE # Uncomment to disable checks of excessive copy-pastes
  - SPELL # Comment to enable checks of spelling mistakes

SHOW_ELAPSED_TIME: true

FILEIO_REPORTER: false
SARIF_REPORTER: true
JSON_REPORTER: true
MARKDOWN_SUMMARY_REPORTER: true